version: '3'

services:
   db:
      image: mongo
      container_name: chatapp-db
      networks:
         - chatapp-network
   api:
      build: ./server
      container_name: chatapp-api
      ports:
         - '5000:5000'
      volumes:
         - './server:/app'
         - '/app/node_modules'
      depends_on:
         - db
      networks:
         - chatapp-network
   ui:
      build: ./client
      container_name: chatapp-ui
      ports:
         - '5173:5173'
      volumes:
         - './client:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      depends_on:
         - api
      networks:
         - chatapp-network
networks:
   chatapp-network:
      driver: bridge
