version: '3.7'

services:
   db:
      image: postgres
      container_name: chatapp-db
      ports:
         - '5433:5432'
      networks:
         - chatapp-network
   api:
      build: ./backend
      container_name: chatapp-api
      ports:
         - '5000:5000'
      volumes:
         - './backend:/app'
         - '/app/node_modules'
      depends_on:
         - db
      networks:
         - chatapp-network
   ui:
      build: ./client
      container_name: chatapp-ui
      ports:
         - '5500:5500'
      volumes:
         - './client:/app'
         - '/app/node_modules'
      stdin_open: true
      tty: true
      depends_on:
         - api
      networks:
         - chatapp-network
networks:
   chatapp-network:
      driver: bridge
